export const AICONSENT_STEPS = [
  { case: 1, step: "open", expected: "pass" },
  { case: 2, step: "consent", expected: "pass" },
  { case: 3, step: "deny", expected: "pass" },
  { case: 4, step: "fallback", expected: "pass" },
  { case: 5, step: "grant", expected: "pass" },
  { case: 6, step: "generate", expected: "pass" },
  { case: 7, step: "save", expected: "pass" },
  { case: 8, step: "clear-history", expected: "pass" },
  { case: 9, step: "open", expected: "pass" },
  { case: 10, step: "consent", expected: "pass" },
  { case: 11, step: "deny", expected: "recover" },
  { case: 12, step: "fallback", expected: "pass" },
  { case: 13, step: "grant", expected: "pass" },
  { case: 14, step: "generate", expected: "pass" },
  { case: 15, step: "save", expected: "pass" },
  { case: 16, step: "clear-history", expected: "pass" },
  { case: 17, step: "open", expected: "pass" },
  { case: 18, step: "consent", expected: "pass" },
  { case: 19, step: "deny", expected: "pass" },
  { case: 20, step: "fallback", expected: "pass" },
  { case: 21, step: "grant", expected: "pass" },
  { case: 22, step: "generate", expected: "recover" },
  { case: 23, step: "save", expected: "pass" },
  { case: 24, step: "clear-history", expected: "pass" },
  { case: 25, step: "open", expected: "pass" },
  { case: 26, step: "consent", expected: "pass" },
  { case: 27, step: "deny", expected: "pass" },
  { case: 28, step: "fallback", expected: "pass" },
  { case: 29, step: "grant", expected: "pass" },
  { case: 30, step: "generate", expected: "pass" },
  { case: 31, step: "save", expected: "pass" },
  { case: 32, step: "clear-history", expected: "pass" },
  { case: 33, step: "open", expected: "recover" },
  { case: 34, step: "consent", expected: "pass" },
  { case: 35, step: "deny", expected: "pass" },
  { case: 36, step: "fallback", expected: "pass" },
  { case: 37, step: "grant", expected: "pass" },
  { case: 38, step: "generate", expected: "pass" },
  { case: 39, step: "save", expected: "pass" },
  { case: 40, step: "clear-history", expected: "pass" },
  { case: 41, step: "open", expected: "pass" },
  { case: 42, step: "consent", expected: "pass" },
  { case: 43, step: "deny", expected: "pass" },
  { case: 44, step: "fallback", expected: "recover" },
  { case: 45, step: "grant", expected: "pass" },
  { case: 46, step: "generate", expected: "pass" },
  { case: 47, step: "save", expected: "pass" },
  { case: 48, step: "clear-history", expected: "pass" },
  { case: 49, step: "open", expected: "pass" },
  { case: 50, step: "consent", expected: "pass" },
  { case: 51, step: "deny", expected: "pass" },
  { case: 52, step: "fallback", expected: "pass" },
  { case: 53, step: "grant", expected: "pass" },
  { case: 54, step: "generate", expected: "pass" },
  { case: 55, step: "save", expected: "recover" },
  { case: 56, step: "clear-history", expected: "pass" },
  { case: 57, step: "open", expected: "pass" },
  { case: 58, step: "consent", expected: "pass" },
  { case: 59, step: "deny", expected: "pass" },
  { case: 60, step: "fallback", expected: "pass" },
] as const;

export function stepsForaiConsent(caseNumber: number): (typeof AICONSENT_STEPS)[number][] {
  return AICONSENT_STEPS.filter((step) => step.case === caseNumber);
}

export function allaiConsentCases(): number[] {
  return [...new Set(AICONSENT_STEPS.map((step) => step.case))];
}
